### try catch finally 执行顺序

1. 先看个正常的case：

```
    public static Integer test1() {
        int i = 1;
        try {
            i++;
            System.out.println("try, i= " + i);
        } catch (Exception e) {
            i++;
            System.out.println("catch, i= " + i);
        } finally {
            i = 3;
            System.out.println("finally, i= " + i);
        }

        return i;
    }
```

执行顺序为：try -> 没有异常则进入 finally，最后返回，结果如下：

```
try, i= 2
finally, i= 3
main i = 3
```
<br>
<br>
<br>

2. 如果把return放到try catch中呢
   
```
    public static Integer test2() {
        int j = 1;
        try {
            j++;
            System.out.println("try, j = " + j);
            return j;
        } catch (Exception e) {
            j++;
            System.out.println("catch, j = " + j);
            return j;
        } finally {
            j = 3;
            System.out.println("finally, j = " + j);
        }
    }
```
输出结果为：
```
try, j = 2
finally, j = 3
main j = 2
```

代码执行顺序 try -> finally，由于finally无论如何都会执行，所以try里的语句并不会直接返回。
在try语句的return中，return返回的引用变量j并不是try语句外定义的引用变量j，而是系统重新定义了一个局部引用j'，
这个引用指向了引用j对应的值2；即使finally中把引用j的值指向10。
<br>
<br>
<br>
3. 如果把返回值换成包装类型呢？开看看如何：
   
```
    public static List<String> test3() {
        List<String> n = new ArrayList<>();
        try {
            n.add("try");
            System.out.println("try, n = " + n.toString());
            return n;
        } catch (Exception e) {
            n.add("catch");
            System.out.println("catch, n = " + n.toString());
            return n;
        } finally {
            n.add("finally");
            System.out.println("finally, n = " + n.toString());
        }
    }
```

返回值如下：

```
try, n = [try]
finally, n = [try, finally]
main n = [try, finally]
```

我们可以看到，finally里面对List n操作生效了，我们知道，基本类型在栈中存储，而非基本类型是存储在堆中的，返回的是堆中的地址，
因此内容被改变了。
<br>
<br>
<br>
4. 在finally中加个return，看看程序从哪里返回：

```
    public static Integer test4() {
        int k = 1;
        try {
            k++;
            System.out.println("try, k = " + k);
            return k;
        } catch (Exception e) {
            k++;
            System.out.println("catch, k = " + k);
            return k;
        } finally {
            k = 3;
            System.out.println("finally, k = " + k);
            return k;
        }
    }
```

执行结果：
```
try, k = 2
finally, k = 3
main k = 3
```

可以发现，最终是从finally返回了结果，也就是说，程序执行try的时候，忽略了try中的return。同理，如果执行到catch，也会忽略掉
catch中的return，最终在finally中返回。
<br>
<br>
另外，finally应避免再次抛出异常，一旦发生，会把try catch中的异常覆盖到，达不到异常信息处理的目的
<br>
<br>
<br>
总结：
    - finally语句总是会执行；
    - 如果try catch中有return语句，finally中没有return，在finally中修改（除包装类型，静态变量，全局变量）的数据不会对try catch
中的返回有影响；
    - 尽量不要在finally中使用return语句，会忽略try catch中的return，也会忽略try cathc中产生的异常，异常被屏蔽，无法得知；
    - finally中应避免再次抛出异常，否则程序只会抛出finally中的异常信息，忽略try catch中的异常信息。
<br>
<br>
<br>
实际项目应用中，finally常用于关闭流或者数据库资源，不做其他额外操作。