### try catch finally 执行顺序

1. 先看个正常的case：

```
    public static Integer test1() {
        int i = 1;
        try {
            i++;
            System.out.println("try, i= " + i);
        } catch (Exception e) {
            i++;
            System.out.println("catch, i= " + i);
        } finally {
            i = 3;
            System.out.println("finally, i= " + i);
        }

        return i;
    }
```

执行顺序为：try -> 没有异常则进入 finally，最后返回，结果如下：

```
try, i= 2
finally, i= 3
main i = 3
```

2. 如果把return放到try catch中呢
   
```
    public static Integer test2() {
        int j = 1;
        try {
            j++;
            System.out.println("try, j = " + j);
            return j;
        } catch (Exception e) {
            j++;
            System.out.println("catch, j = " + j);
            return j;
        } finally {
            j = 3;
            System.out.println("finally, j = " + j);
        }
    }
```
输出结果为：
```
try, j = 2
finally, j = 3
main j = 2
```

代码执行顺序 try -> finally，由于finally无论如何都会执行，所以try里的语句并不会直接返回。
在try语句的return中，return返回的引用变量j并不是try语句外定义的引用变量j，而是系统重新定义了一个局部引用j'，
这个引用指向了引用j对应的值2；即使finally中把引用j的值指向10